In [1]:
import torch
import numpy as np

## 텐서 초기화하기

In [20]:
# torch.tensor(자료형)
# Tensors can be created directly from data.
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [21]:
# torch.from_numpy(넘파이)
# numpy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [22]:
# torch.ones_like(텐서), torch.rand_like(텐서)
# 다른 텐서로부터 생성하기, shape, datatype을 명시하지 않으면 그대로 유지한다.
## x_data 속성 유지하면서 값은 0
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n ")

## x_data 속성 유지하면서 값을 랜덤하게 뽑기
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 
 
Random Tensor: 
 tensor([[0.1032, 0.7738],
        [0.4528, 0.2385]]) 



In [24]:
# torch.rand(차원), torch.ones(차원), torch.zeros(차원)
# 차원 지정해서 생성 
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8499, 0.9684, 0.0308],
        [0.8200, 0.6918, 0.3753]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## 텐서의 속성

In [29]:
tensor = torch.rand(3,4)
tensor

tensor([[0.0954, 0.1122, 0.0245, 0.8891],
        [0.0493, 0.0637, 0.2255, 0.0233],
        [0.1829, 0.3898, 0.0251, 0.9914]])

In [30]:
# shape, dtype, device
print(f"Shape of tensor {tensor.shape}")
print(f"Datatype of tensor {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor torch.Size([3, 4])
Datatype of tensor torch.float32
Device tensor is stored on: cpu


## 텐서 연산
전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 임의 샘플링(random sampling) 등, 100가지 이상의 텐서 연산들을 확인할 수 있다.

In [31]:
# GPU가 존재하면 텐서를 이동합니다.
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [43]:
# NumPy 식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4,4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [48]:
# torch.cat 
# 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [51]:
# tensor.mul(), tensor*tensor
# 텐서 요소별 곱
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor * tensor \n {tensor*tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [54]:
# tensor.matmul(전치 행렬 텐서), tensor @ tensor.T
# 행렬 곱
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n ")
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 
 
tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [55]:
# tensor.add_(5)
# 바꿔치기 연산...
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환

In [57]:
# CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 번경된다.
## 텐서를 넘파이배열로
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [58]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [59]:
# 넘파이 배열을 텐서로 
n = np.ones(5)
t = torch.from_numpy(n)

In [60]:
# 넘파이 배열의 변경 사항이 텐서에 반영된다.
np.add(n, 1, out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
