# Numpy1

In [1]:
import numpy as np

## linsapce 함수

1차원 배열 만들기, 그래프 그리기에서 수평축의 간격 만들기 등에 편리하게 사용된다.

x = np.linspace(start, stop, num)
* start : 배열의 시작값
* stop : 배열의 끝 값
* num : start와 stop 사이를 몇 개의 간격으로 요소를 만들 것인지 나타내는 값(디폴트는 50개의 수열이다.)

In [16]:
x1 = np.linspace(0, 10)
print(x1)
print(x1.shape)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
(50,)


In [15]:
x2 = np.linspace(10, 20, 11)
print(x2)
print(x2.shape)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
(11,)


## reshape() 함수
현재 배열의 차원을 변경하여 행렬을 반환할 때 많이 사용된다. 인자 개수로 차원이 결정된다.

**np.reshape(변경할 배열, 차원)**, **변경할 배열.reshape(차원)**

### 1차원과 2차원 변환

In [20]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.reshape(a, (2,4))
print(b)
print('\n')
c = np.reshape(a,(4,2))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 1차원 3차원 변환

In [22]:
a = np.arange(1,9)
b = a.reshape(2,2,2)
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### reshape에서 -1 의미

In [23]:
x = np.arange(12)
x = x.reshape(3,4)

In [25]:
# 열의 개수를 1개로 하고 행은 자동으로 채워진다.
x.reshape(-1, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [26]:
# 열의 개수는 2개로 하고 행은 자동으로 채워진다.
x.reshape(-1,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
# 열의 개수는 3개로 하고 행은 자동으로 채워진다.
x.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
# 행의 개수는 1개로 하고 열은 자동으로 채워진다.
x.reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [29]:
# 행의 개수는 2개로 하고 열은 자동으로 채워진다.
x.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [30]:
# 행의 개수는 3개로 하고 열은 자동으로 채워진다.
x.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# reshape(-1)인 경우 1차원 배열을 반환한다. 모양상 x.reshape(1,-1)과 같다.
x.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## np.random

### numpy.random.rand
0~1 사이의 값을 uniform distirbution 균일 분포의 값을 return 하는 함수이다.

In [32]:
np.random.rand()

0.15984089700584048

In [33]:
# 1 dim
np.random.rand(3)

array([0.32368985, 0.81262766, 0.22485212])

In [34]:
# 2 dim
np.random.rand(3,2)

array([[0.62644086, 0.95238216],
       [0.68650477, 0.05627153],
       [0.61090732, 0.82663069]])

### numpy.random.randn
정규분포 값을 return 하는 함수이다. -1~1 사이의 값을 얻을 수 있다.

In [35]:
np.random.randn()

0.728184167237301

In [36]:
np.random.randn(3)

array([-1.92715918, -0.1851627 ,  2.45310407])

In [37]:
np.random.randn(3,2)

array([[-0.00983837, -0.33442717],
       [ 0.83263486, -1.85040465],
       [-0.0705202 , -0.43331888]])

## concatenate
numpy 배열들을 하나로 합치는데 이용된다.

### 1차원 끼리

In [38]:
A1 = np.array([1,2,3])
B1 = np.array([4,5,6])

np.concatenate((A1, B1), axis=0)

array([1, 2, 3, 4, 5, 6])

### 2차원 끼리

In [41]:
A2 = np.array([[1,2,3], [10,20, 30]])
B2 = np.array([[4,5,6], [40, 50, 60]])
print(A2)
print(B2)

[[ 1  2  3]
 [10 20 30]]
[[ 4  5  6]
 [40 50 60]]


In [40]:
# axis = 0
np.concatenate((A2, B2), axis = 0)

array([[ 1,  2,  3],
       [10, 20, 30],
       [ 4,  5,  6],
       [40, 50, 60]])

In [42]:
# axis = 1
np.concatenate((A2, B2), axis = 1)

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60]])

### 3차원 끼리

In [44]:
A3 = np.array([[[1,2,3,4], [10,20,30,40]],[[100,200,300,400],[10000,2000,3000, 4000]]])
B3 = np.array([[[5,6,7,8], [50,60,70,80]],[[500,600,700,800],[50000,6000,7000, 8000]]])

print(A3)
print(B3)

[[[    1     2     3     4]
  [   10    20    30    40]]

 [[  100   200   300   400]
  [10000  2000  3000  4000]]]
[[[    5     6     7     8]
  [   50    60    70    80]]

 [[  500   600   700   800]
  [50000  6000  7000  8000]]]


In [45]:
np.concatenate((A3, B3), axis=0)

array([[[    1,     2,     3,     4],
        [   10,    20,    30,    40]],

       [[  100,   200,   300,   400],
        [10000,  2000,  3000,  4000]],

       [[    5,     6,     7,     8],
        [   50,    60,    70,    80]],

       [[  500,   600,   700,   800],
        [50000,  6000,  7000,  8000]]])

In [46]:
np.concatenate((A3, B3), axis=1)

array([[[    1,     2,     3,     4],
        [   10,    20,    30,    40],
        [    5,     6,     7,     8],
        [   50,    60,    70,    80]],

       [[  100,   200,   300,   400],
        [10000,  2000,  3000,  4000],
        [  500,   600,   700,   800],
        [50000,  6000,  7000,  8000]]])

In [48]:
np.concatenate((A3, B3), axis=2)

array([[[    1,     2,     3,     4,     5,     6,     7,     8],
        [   10,    20,    30,    40,    50,    60,    70,    80]],

       [[  100,   200,   300,   400,   500,   600,   700,   800],
        [10000,  2000,  3000,  4000, 50000,  6000,  7000,  8000]]])